### ISSUE TITLE
language iso code. 

### ISSUE THREAD

**Issue by martingg88** [rxaviers/cldr-data-full-npm#1]
any idea how you handle the language come with region (etc: en-US, en-GB) to pick the right cldr folder?

it is a bit confused that some cldr folder do not have region, but they do have following format. 
it is hard to pick the right cldr folder if i have this format ms-MY

ms-Latn-MY

**Comment by rxaviers** [comment]
Hi @martingg88, when I first start using CLDR I also had this question. But, it's a matter of understanding it. You'll notice CLDR has done a great job structuring the data. Read [Default Content](http://www.unicode.org/reports/tr35/tr35-info.html#Default_Content).

If you're using cldr-data on JavaScript, please consider using [cldrjs](https://github.com/rxaviers/cldrjs) to traverse/manipulate the data. A somewhat related documentation that might interest you is https://github.com/rxaviers/cldrjs/blob/master/doc/bundle_lookup_matcher.md.

If you need further assistance feel free to add comments.
